version: "3"

services:
  rethinkdb:
    container_name: rethinkdb
    image: rethinkdb:2.3
    restart: unless-stopped
    ports:
      - 28015:28015
      - 18080:8080
    volumes:
        - "rethinkdb-data:/data"
    command: "rethinkdb --bind all --cache-size 2048"

  adb:
    container_name: adb
    image: devicefarmer/adb:latest
    restart: unless-stopped
    volumes: 
      - "/dev/bus/usb:/dev/bus/usb"
    privileged: true
  stf_app:
    container_name: stf_app
    image: devicefarmer/stf
    command: stf app --port 3000 --auth-url https://stf.ewther.science/auth/mock/ --websocket-url wss://stf.ewther.science/
    ports:
      - 3100:3000
    environment:
      - SECRET=nosecret
      - RETHINKDB_PORT_28015_TCP=tcp://rethinkdb:28015
      - STF_ADMIN_EMAIL=admin@local.loc
      - STF_ADMIN_NAME=admin
    depends_on:
      - rethinkdb
      - stf_websocket
    restart: always
  stf_auth_mock:
    container_name: stf_auth_mock
    image: devicefarmer/stf
    command: stf auth-mock --port 3000 --app-url https://stf.ewther.science/
    environment:
      - SECRET=nosecret
      - RETHINKDB_PORT_28015_TCP=tcp://rethinkdb:28015
      - STF_ADMIN_EMAIL=admin@local.loc
      - STF_ADMIN_NAME=admin
    ports:
      - 3200:3000
    restart: always
    depends_on:
      - rethinkdb
      - stf_migrate
  stf_migrate:
    container_name: stf_migrate
    image: devicefarmer/stf
    command: stf migrate
    environment:
      - SECRET=nosecret
      - RETHINKDB_PORT_28015_TCP=tcp://rethinkdb:28015
      - STF_ADMIN_EMAIL=admin@local.loc
      - STF_ADMIN_NAME=admin
      - STF_ROOT_GROUP_NAME=admin
    depends_on:
      - rethinkdb
  stf_processor:
    container_name: stf_processor
    image: devicefarmer/stf
    command: stf processor --connect-app-dealer tcp://appside.stf.ewther.science:7160 --connect-dev-dealer tcp://devside.stf.ewther.science:7260
    environment:
      - SECRET=nosecret
      - RETHINKDB_PORT_28015_TCP=tcp://rethinkdb:28015
      - STF_ADMIN_EMAIL=admin@local.loc
      - STF_ADMIN_NAME=admin
      - STF_ROOT_GROUP_NAME=admin
    depends_on:
      - rethinkdb
      - stf_triproxy_dev
      - adb
    restart: always
  stf_provider:
    container_name: stf_provider
    image: devicefarmer/stf
    command: stf provider  --name "PC1" --connect-sub tcp://devside.stf.ewther.science:7250 --connect-push tcp://devside.stf.ewther.science:7270 --storage-url https://stf.ewther.science/  --public-ip 0.0.0.0  --min-port=15000  --max-port=25000  --heartbeat-interval 10000  --screen-ws-url-pattern "wss://stf.ewther.science/d/floor4/<%= serial %>/<%= publicPort %>/" --adb-host adb
    environment:
      - SECRET=nosecret
      - RETHINKDB_PORT_28015_TCP=tcp://rethinkdb:28015
      - STF_ADMIN_EMAIL=admin@local.loc
      - STF_ADMIN_NAME=admin
      - STF_ROOT_GROUP_NAME=admin
    depends_on:
      - adb
      - rethinkdb
      - stf_triproxy_dev
    restart: always
    ports:
      - 15000-15010:15000-15010
  stf_reaper:
    container_name: stf_reaper
    image: devicefarmer/stf
    command: stf reaper dev --connect-push tcp://devside.stf.ewther.science:7270 --connect-sub tcp://appside.stf.ewther.science:7150 --heartbeat-timeout 300000
    environment:
      - SECRET=nosecret
      - RETHINKDB_PORT_28015_TCP=tcp://rethinkdb:28015
      - STF_ADMIN_EMAIL=admin@local.loc
      - STF_ADMIN_NAME=admin
      - STF_ROOT_GROUP_NAME=admin
    depends_on:
      - adb
      - rethinkdb
      - stf_triproxy_dev
    restart: always
  stf_storage_plugin_apk:
    container_name: stf_storage_plugin_apk
    image: devicefarmer/stf
    command: stf storage-plugin-apk --port 3000 --storage-url https://stf.ewther.science/
    ports:
      - 3300:3000
    environment:
      - SECRET=nosecret
      - RETHINKDB_PORT_28015_TCP=tcp://rethinkdb:28015
      - STF_ADMIN_EMAIL=admin@local.loc
      - STF_ADMIN_NAME=admin
      - STF_ROOT_GROUP_NAME=admin
    depends_on:
      - adb
      - rethinkdb
    restart: always
  stf_storage_plugin_image:
    container_name: stf_storage_plugin_image
    image: devicefarmer/stf
    command: stf storage-plugin-image --port 3000 --storage-url https://stf.ewther.science/
    ports:
      - 3400:3000
    environment:
      - SECRET=nosecret
      - RETHINKDB_PORT_28015_TCP=tcp://rethinkdb:28015
      - STF_ADMIN_EMAIL=admin@local.loc
      - STF_ADMIN_NAME=admin
      - STF_ROOT_GROUP_NAME=admin
    depends_on:
      - adb
      - rethinkdb
    restart: always
  stf_storage_plugin_temp:
    container_name: stf_storage_plugin_temp
    image: devicefarmer/stf
    command: stf storage-temp --port 3000 --save-dir /data
    ports:
      - 3500:3000
    environment:
      - SECRET=nosecret
      - RETHINKDB_PORT_28015_TCP=tcp://rethinkdb:28015
      - STF_ADMIN_EMAIL=admin@local.loc
      - STF_ADMIN_NAME=admin
      - STF_ROOT_GROUP_NAME=admin
    depends_on:
      - adb
      - rethinkdb
    restart: always
  stf_triproxy_app:
    container_name: stf_triproxy_app
    image: devicefarmer/stf
    command: stf triproxy app --bind-pub "tcp://*:7150" --bind-dealer "tcp://*:7160" --bind-pull "tcp://*:7170"
    ports:
      - 7150:7150
      - 7160:7160
      - 7170:7170
    environment:
      - SECRET=nosecret
      - RETHINKDB_PORT_28015_TCP=tcp://rethinkdb:28015
      - STF_ADMIN_EMAIL=admin@local.loc
      - STF_ADMIN_NAME=admin
      - STF_ROOT_GROUP_NAME=admin
    depends_on:
      - adb
      - rethinkdb
    restart: always
  stf_triproxy_dev:
    container_name: stf_triproxy_dev
    image: devicefarmer/stf
    command: stf triproxy dev --bind-pub "tcp://*:7250" --bind-dealer "tcp://*:7260" --bind-pull "tcp://*:7270"
    ports:
      - 7250:7250
      - 7260:7260
      - 7270:7270
    environment:
      - SECRET=nosecret
      - RETHINKDB_PORT_28015_TCP=tcp://rethinkdb:28015
      - STF_ADMIN_EMAIL=admin@local.loc
      - STF_ADMIN_NAME=admin
      - STF_ROOT_GROUP_NAME=admin
    depends_on:
      - adb
      - rethinkdb
      - stf_migrate
    restart: always
  stf_websocket:
    container_name: stf_websocket
    image: devicefarmer/stf
    command: stf websocket --port 3000 --storage-url https://stf.ewther.science/ --connect-sub tcp://appside.stf.ewther.science:7150 --connect-push tcp://appside.stf.ewther.science:7170
    ports:
      - 3600:3000
    environment:
      - SECRET=nosecret
      - RETHINKDB_PORT_28015_TCP=tcp://rethinkdb:28015
      - STF_ADMIN_EMAIL=admin@local.loc
      - STF_ADMIN_NAME=admin
      - STF_ROOT_GROUP_NAME=admin
    depends_on:
      - adb
      - rethinkdb
      - stf_triproxy_app
    restart: always
  stf_api:
    container_name: stf_api
    image: devicefarmer/stf
    command: stf api --port 3000 --connect-sub tcp://appside.stf.ewther.science:7150 --connect-push tcp://appside.stf.ewther.science:7170 --connect-sub-dev tcp://devside.stf.ewther.science:7250 --connect-push-dev tcp://devside.stf.ewther.science:7270
    ports:
      - 3700:3000
    environment:
      - SECRET=nosecret
      - RETHINKDB_PORT_28015_TCP=tcp://rethinkdb:28015
      - STF_ADMIN_EMAIL=admin@local.loc
      - STF_ADMIN_NAME=admin
      - STF_ROOT_GROUP_NAME=admin
    depends_on:
      - adb
      - rethinkdb
      - stf_triproxy_dev
      - stf_triproxy_app
    restart: always
  stf_group_engine:
    container_name: stf_group_engine
    image: devicefarmer/stf
    command: stf groups-engine --connect-sub tcp://appside.stf.ewther.science:7150 --connect-push tcp://appside.stf.ewther.science:7170 --connect-sub-dev tcp://devside.stf.ewther.science:7250 --connect-push-dev tcp://devside.stf.ewther.science:7270
    environment:
      - SECRET=nosecret
      - RETHINKDB_PORT_28015_TCP=tcp://rethinkdb:28015
      - STF_ADMIN_EMAIL=admin@local.loc
      - STF_ADMIN_NAME=admin
      - STF_ROOT_GROUP_NAME=admin
    depends_on:
      - adb
      - rethinkdb
      - stf_triproxy_app
      - stf_triproxy_dev
    restart: always

volumes:
  rethinkdb-data: {}
